# Generated by Django 5.0.6 on 2024-07-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_name', models.CharField(max_length=255)),
                ('de_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='issui_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issui_name', models.CharField(max_length=255)),
                ('issui_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='so_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_firstname', models.CharField(max_length=255)),
                ('so_lastname', models.CharField(max_length=255)),
                ('so_phone', models.IntegerField()),
                ('so_department', models.CharField(max_length=255, null=True)),
                ('so_description', models.TextField(null=True)),
            ],
        ),
    ]
