# Generated by Django 5.0.6 on 2024-07-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noc_phonebook', '0001_initial'),
    ]

    operations = [
    ]
